# Generated by Django 4.1.3 on 2026-01-23 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('html', 'HTML')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], max_length=10)),
                ('content', models.TextField()),
                ('page_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.pagecontent')),
            ],
        ),
    ]
