# Generated by Django 4.1.3 on 2026-03-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='logo',
            field=models.ImageField(blank=True, upload_to='certifications/'),
        ),
    ]
